---
- hosts: ansible_web
  become: yes
  vars_files:
    - vars/default.yml
  user: "{{ default_user }}"
  tasks:
    - include: tasks/uwsgi.yml
  handlers:
    - name: start uwsgi
      shell: /usr/local/bin/uwsgi --emperor /etc/uwsgi/vassals --daemonize /var/log/uwsgi-emperor.log
