---
- include: ../pythondev/pythondev-playbook.yml
- hosts: ansible_celery
  vars_files:
    # - ../web/vars/default.yml
    - vars/default.yml
  tasks:
    - include: ../web/tasks/web.yml
    - include: tasks/celery.yml
  handlers:
    - name: restart rabbitmq
      sudo: yes
      service: name=rabbitmq-server state=restarted
    - name: start celery
      command: sudo /etc/init.d/celeryd start
