default_user: vagrant
# App
git_repo: git@github.com:garyayo/SaltStack-mysite.git
git_branch: ansible-dev
project_path: ~/mysite
# Virtualenv
requirements_file: /home/vagrant/mysite/requirements.txt
virtualenv_path: /home/vagrant/testenv
