- name: Ensure Python uwsgi plugin is installed via pip
  pip: name=uwsgi
- name: Create uwsgi path
  file: path=/etc/uwsgi/vassals/ state=directory
- name: Ensure runs with the latest uwsgi configuration file
  template:
    src: "templates/{{ uwsgi_conf_file }}"
    dest: "/etc/uwsgi/vassals/{{ uwsgi_conf_file }}"
    owner: "{{ default_user }}"
- name: Copy rc.local over
  template: "src=templates/rc.local dest=/etc/rc.local owner={{ default_user }}"
  notify:
    - start uwsgi
