---
- hosts: [ansible_web, ansible_celery]
  become: yes
  vars_files:
    - vars/default.yml
  user: "{{ default_user }}"
  tasks:
    - include: tasks/pythondev.yml
  # handlers:
  #   - include: handlers/app.yml
