---
- hosts: ansible_web
  become: yes
  vars_files:
    - vars/default.yml
  user: "{{ default_user }}"
  tasks:
    - include: tasks/nginx.yml
  handlers:
    - name: start nginx
      service: name=nginx state=started
    - name: restart nginx
      action: service name=nginx state=restarted
