- name: Install rabbitmq-server
  become: yes
  apt: pkg=rabbitmq-server state=installed update_cache=true

- name: Copy rabbitmq.config over
  become: yes
  template: src=templates/rabbitmq.config dest=/etc/rabbitmq/rabbitmq.config

- name: Create rabbitmq user
  become: yes
  command: rabbitmqctl add_user myuser mypassword
- name: Create rabbitmq vhost
  become: yes
  command: rabbitmqctl add_vhost myvhost
- name: Set rabbitmq user tags
  become: yes
  command: rabbitmqctl set_user_tags myuser mytag
- name: Set rabbitmq permissions
  become: yes
  command: rabbitmqctl set_permissions -p myvhost myuser ".*" ".*" ".*"


- name: Pip install celery
  become: yes
  pip: name=celery

- name: Copy default/celeryd over
  become: yes
  template: src=templates/default_celeryd dest=/etc/default/celeryd

- name: Copy init.d/celeryd over
  become: yes
  template: src=templates/init.d_celeryd dest=/etc/init.d/celeryd mode=0755


- name: Create celery group
  become: yes
  group: name=celery state=present


- name: Create celery user
  become: yes
  user: name=celery groups=celery state=present

- name: chown /var/log/celery
  become: yes
  file: path=/var/log/celery owner=celery group=celery state=directory

- name: chown /var/run/celery
  become: yes
  file: path=/var/run/celery owner=celery group=celery state=directory
  notify:
    - restart rabbitmq
    - start celery
