---
- hosts: ansible_db
  become: yes
  vars_files:
    - vars/default.yml
  user: "{{ default_user }}"
  tasks:
    - include: tasks/postgres.yml
  handlers:
    - name: restart postgres
      action: service name=postgresql state=restarted


#Setup mydb database
- hosts: ansible_db
  become: yes
  vars_files:
    - vars/default.yml
  become_user: postgres
  tasks:
    - name: Create database
      postgresql_db: name="{{ dbname }}"
