---
- hosts: ansible_cache
  become: yes
  vars_files:
    - vars/default.yml
  user: "{{ default_user }}"
  tasks:
    - include: tasks/redis.yml
  handlers:
    - name: start redis
      command: /etc/init.d/redis_6379 start
